name: final_output
description: Aggregated transaction metrics by user segment
columns:
  - name: segment
    dtype: str
    description: Combined bucketed age and log-age identifier
  - name: amount
    dtype: float
    description: Average amount of transactions per segment
  - name: high_value
    dtype: int
    description: Total count of high-value transactions per segment
