name: user
description: User table with id, user_id, and age
path: ../../data/user.csv
columns:
  - name: id
    dtype: str
    description: Row ID
  - name: user_id
    dtype: str
    description: Unique identifier for each user
  - name: age
    dtype: int
    description: Age of the user
