depends:
  - user_filter.yaml
  - trans_summary.yaml

processes:
  - name: transaction_enrichment

    tables:
      - name: user
        path: ../../output/filtered_users.csv
        schema: ${schema.user.columns}

      - name: trans
        path: ../../output/filtered_transactions.csv
        schema: ${schema.trans.columns}

    steps:
      - name: filter_users_main
        with: user
        mutate:
          - filter: age > ${params.min_age}
          - derive: |
              log_age = log(age)
              age_bucket = age // 10 * 10
          - select: [user_id, log_age, age_bucket]
        as: filtered_users
        when: ${params.test}

      - name: filter_transactions_main
        with: trans
        mutate:
          - filter: amount > 1000
        as: filtered_trans

      - name: merge_transactions
        with: [filtered_users, filtered_trans]
        transform: merge(left=filtered_users, right=filtered_trans, on='user_id')
        as: enriched

      - name: enrich_transactions
        with: enriched
        mutate:
          - derive: |
              high_value = amount > 10000
          - select: ${params.enrich_transactions.columns}
        as: final_output

    dumps:
      - output: final_output
        path: ../../output/final_output.csv
        schema: ${schema.enriched.columns}
