processes:
  - name: trans_summary
    description: Summarize transaction amounts
    tables:
      - name: trans
        path: ../../data/transaction.csv
    steps:
      - name: summarize_transactions
        with: trans
        mutate:
          - filter: amount > 0
          - derive: is_large = amount > 5000
          - select: [user_id, amount, is_large]
        as: filtered_transactions
    dumps:
      - output: filtered_transactions
        path: ../../output/filtered_transactions.csv
