name: transaction_summary_template
processes:
  - name: trans_summary
    description: Summarize transaction amounts
    io:
      inputs:
        - name: trans
          io_type: csv
          path: ../../data/transaction.csv
          schema: trans
      outputs:
        - name: filtered_transactions
          io_type: csv
          path: ../../source/outputs/filtered_transactions.csv
          schema: filtered_transactions
    steps:
      - name: summarize_transactions
        with: trans
        mutate:        
          - derive: |
              amount = （アマウント）
        mutate:
          - filter: amount > 0
          - derive: is_large = amount > 5000
          - select: [user_id, amount, is_large]
        as: filtered_transactions
