processes:
  - name: user_filter
    description: Filter users under 30
    tables:
      - name: user
        path: ../../data/user.csv
    steps:
      - name: filter_users
        with: user
        mutate:
          - filter: age < 30
          - derive: age_group = age // 10
          - select: [user_id, age, age_group]
        as: filtered_users
    dumps:
      - output: filtered_users
        path: ../../output/filtered_users.csv
