params:
  test: true
  min_age: 18
  enrich_transactions:
    columns:
      - "user_id"
      - "log_age"
      - "amount"
      - "high_value"

schema:
  user:
    description: User table with age and grouping
    columns:
      - name: id
        dtype: str
        description: id
      - name: user_id
        dtype: str
        description: Unique identifier for each user
      - name: age
        dtype: int
        description: Age of the user
      - name: age_group
        dtype: int
        description: Age group of the user, calculated as age // 10

  trans:
    description: Transaction table with amounts and flags
    columns:
      - name: id
        dtype: str
        description: id
      - name: user_id
        dtype: str
        description: Unique identifier for each user
      - name: amount
        dtype: float
        description: Amount of the transaction

  final_output:
    description: Enriched user and transaction data
    columns:
      - name: user_id
        dtype: str
        description: Unique identifier for each user
      - name: log_age
        dtype: float
        description: Logarithm of the user's age
      - name: amount
        dtype: int
        description: Amount of the transaction
      - name: high_value
        dtype: bool
        description: Flag indicating if the transaction amount is greater than 10000
