settings:
  generate:
    path: ../scripts/generated_user_flow.py
    execute: true
custom_functions:
  define_funcs:
    - ../../custom_functions/define_funcs.py
  transform_funcs:
    - ../../custom_functions/transform_funcs.py
processes:
  - process: transaction_enrichment
    description: Enrich user data with transaction details
    tables:
      - name: user
        path: ../data/user.csv
      - name: trans
        path: ../data/transaction.csv
    steps:
      - with: user
        filter: age > 18
        define: |
          log_age = log(age)
          age_bucket = age // 10 * 10
        select: [user_id, log_age, age_bucket]
      - with: trans
        filter: amount > 1000
      - transform: enriched = merge(left=user, right=trans, on='user_id')
      - with: enriched
        define: high_value = amount > 10000
        select: [user_id, log_age, amount, high_value]
    dumps:
      - return: enriched
        path: ../output/final_output.csv
