graph TB

%% ==== Template dependencies ====
T_user_filter --> T_main_template
T_trans_summary --> T_main_template

%% ==== Processes in main_template ====
subgraph T_main_template ["main_template"]
  subgraph P_transaction_enrichment ["transaction_enrichment"]
    S_../output/filtered_users.csv(["../output/filtered_users.csv"])
    S_../output/filtered_transactions.csv(["../output/filtered_transactions.csv"])
    S_filter_users_main(["filter_users_main"])
    S_filter_transactions_main(["filter_transactions_main"])
    S_merge_transactions(["merge_transactions"])
    S_enrich_transactions(["enrich_transactions"])
    S_../output/filtered_users.csv --> S_filter_users_main
    S_../output/filtered_transactions.csv --> S_filter_transactions_main
    S_filter_users_main --> S_merge_transactions
    S_filter_transactions_main --> S_merge_transactions
    S_merge_transactions --> S_enrich_transactions
    S_enrich_transactions --> S_../output/final_output.csv
  end
end

%% ==== Processes in trans_summary ====
subgraph T_trans_summary ["trans_summary"]
  subgraph P_trans_summary ["trans_summary"]
    S_../data/transaction.csv(["../data/transaction.csv"])
    S_summarize_transactions(["summarize_transactions"])
    S_../data/transaction.csv --> S_summarize_transactions
    S_summarize_transactions --> S_../output/filtered_transactions.csv
  end
end

%% ==== Processes in user_filter ====
subgraph T_user_filter ["user_filter"]
  subgraph P_user_filter ["user_filter"]
    S_../data/user.csv(["../data/user.csv"])
    S_filter_users(["filter_users"])
    S_../data/user.csv --> S_filter_users
    S_filter_users --> S_../output/filtered_users.csv
  end
end